name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: okkema/actions/terraform@main
        with:
          terraform-token: ${{ secrets.TF_API_TOKEN }}
        env:
          TF_VAR_github_repository: okkema/ui
