name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: okkema/actions/terraform@v2
        with:
          terraform-token: ${{ secrets.TF_API_TOKEN }}
